### ISSUE TITLE
No longer on CRAN?

### ISSUE THREAD

**Issue by adamhsparks** [chgigot/epiphy#3]
As per the CRAN website for the package: https://cran.r-project.org/web/packages/epiphy/index.html

>Package ‘epiphy’ was removed from the CRAN repository.

>Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/epiphy).

>Archived on 2022-03-10 as check problems were not corrected in time.

>A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-03-10_check_results_epiphy.html).

Are there plans to fix the issues and resubmit?

**Comment by chgigot** [comment]
Hi @adamhsparks
The package is now back on CRAN.
